import { Dimensions, StyleSheet } from "react-native";

const SCREEN_WIDTH = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 12,
    color: "#5D5B7A",
    fontSize: 15,
    fontWeight: "700",
  },
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    overflow: "hidden",
  },
  waterFill: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(120,194,242,0.34)",
    overflow: "hidden",
    zIndex: 0,
  },
  waveOne: {
    position: "absolute",
    top: -12,
    left: -40,
    width: "120%",
    height: 32,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.42)",
  },
  waveTwo: {
    position: "absolute",
    top: 4,
    left: -30,
    width: "120%",
    height: 24,
    borderRadius: 50,
    backgroundColor: "rgba(120,190,240,0.18)",
  },
  header: {
    height: 65,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 10,
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 27,
    fontWeight: "800",
    color: "#29264E",
  },
  tabs: {
    height: 57,
    marginHorizontal: 25,
    borderRadius: 30,
    backgroundColor: "#DCE5F0",
    padding: 5,
    flexDirection: "row",
    zIndex: 10,
  },
  tab: {
    flex: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTab: {
    backgroundColor: "#FFFFFF",
  },
  tabText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#77768B",
  },
  activeTabText: {
    color: "#29264E",
    fontWeight: "800",
  },
  slider: {
    width: SCREEN_WIDTH * 2,
    flex: 1,
    flexDirection: "row",
  },
  page: {
    width: SCREEN_WIDTH,
    flexGrow: 0,
    flexShrink: 0,
  },
  date: {
    height: 58,
    marginHorizontal: 25,
    marginTop: 12,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    zIndex: 10,
  },
  dateText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#29264E",
    textTransform: "capitalize",
  },
  historicoBadge: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.75)",
    zIndex: 10,
  },
  historicoBadgeText: {
    color: "#6575F1",
    fontSize: 11,
    fontWeight: "800",
  },
  main: {
    flex: 1,
    alignItems: "center",
    position: "relative",
    paddingTop: 20,
    zIndex: 5,
  },
  amount: {
    fontSize: 58,
    fontWeight: "900",
    color: "#28254D",
  },
  amountUnit: {
    fontSize: 30,
    fontWeight: "700",
  },
  percentage: {
    fontSize: 29,
    fontWeight: "800",
    color: "#77768B",
    marginTop: -5,
  },
  waterScene: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  drop: {
    width: 145,
    height: 145,
    borderRadius: 75,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
  spark: {
    position: "absolute",
    width: 15,
    height: 15,
    backgroundColor: "#A9BDF4",
    transform: [{ rotate: "45deg" }],
  },
  sparkOne: {
    left: "20%",
    top: "35%",
  },
  sparkTwo: {
    right: "18%",
    top: "45%",
  },
  sparkThree: {
    left: "35%",
    bottom: "25%",
  },
  scale: {
    position: "absolute",
    left: 7,
    top: 20,
    bottom: 20,
    justifyContent: "space-between",
  },
  scaleText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#77768B",
  },
  waterButtons: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    zIndex: 10,
  },
  bottomButtons: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 18,
    paddingBottom: 18,
    zIndex: 10,
  },
  customButton: {
    width: 105,
    height: 105,
    borderRadius: 53,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  customButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#438FE8",
    marginTop: 2,
  },
  addButton: {
    width: 105,
    height: 105,
    borderRadius: 53,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  addText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#438FE8",
    marginTop: -7,
  },
  buttonPressed: {
    transform: [{ scale: 0.94 }],
  },
  customOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(13,27,62,0.25)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 25,
    zIndex: 80,
  },
  customOverlayColor: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(13,27,62,0.12)",
  },
  customCard: {
    width: "100%",
    maxWidth: 380,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.97)",
    paddingHorizontal: 24,
    paddingVertical: 26,
    alignItems: "center",
    elevation: 15,
    shadowColor: "#244C7E",
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: {
      width: 0,
      height: 8,
    },
  },
  customIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#E6F5FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  customTitle: {
    fontSize: 23,
    fontWeight: "900",
    color: "#29264E",
  },
  customDescription: {
    marginTop: 7,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    color: "#77768B",
    maxWidth: 290,
  },
  customInputWrapper: {
    width: "100%",
    height: 58,
    marginTop: 20,
    borderWidth: 1.5,
    borderColor: "#94D8F4",
    borderRadius: 17,
    backgroundColor: "#F8FCFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  customInput: {
    flex: 1,
    height: "100%",
    fontSize: 20,
    fontWeight: "800",
    color: "#29264E",
    textAlign: "center",
  },
  customInputUnit: {
    fontSize: 15,
    fontWeight: "800",
    color: "#5399CD",
  },
  customLimit: {
    marginTop: 7,
    fontSize: 11,
    fontWeight: "700",
    color: "#9998AA",
  },
  customActions: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  customCancelButton: {
    flex: 1,
    height: 50,
    borderRadius: 16,
    backgroundColor: "#EEF3F8",
    alignItems: "center",
    justifyContent: "center",
  },
  customCancelText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#5D5B7A",
  },
  customConfirmButton: {
    flex: 1,
    height: 50,
    borderRadius: 16,
    backgroundColor: "#5399CD",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  customConfirmText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  successWrapper: {
    width: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    zIndex: 20,
    paddingHorizontal: 12,
    paddingBottom: 24,
  },
  successCard: {
    width: "88%",
    maxWidth: 360,
    backgroundColor: "rgba(255,255,255,0.97)",
    borderRadius: 30,
    paddingHorizontal: 25,
    paddingVertical: 24,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    shadowColor: "#5968D8",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 8,
    },
  },
  successIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#6878EF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  successSmall: {
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: "900",
    color: "#8B89A4",
  },
  successTitle: {
    fontSize: 27,
    fontWeight: "900",
    color: "#29264E",
    marginTop: 3,
  },
  successText: {
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
    color: "#666580",
    fontWeight: "600",
    marginTop: 7,
  },
  successLine: {
    width: 55,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#A8B4FF",
    marginVertical: 13,
  },
  successTomorrow: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    color: "#6575F1",
    fontWeight: "800",
  },
  successBubble: {
    position: "absolute",
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: "#A9BDF4",
  },
  bubbleA: {
    left: "18%",
    top: 5,
  },
  bubbleB: {
    right: "17%",
    top: 15,
    width: 11,
    height: 11,
  },
  previousDayCard: {
    width: "88%",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingVertical: 18,
    alignItems: "center",
    marginBottom: 18,
    zIndex: 10,
    elevation: 7,
  },
  previousDayIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#6878EF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  previousDayTitle: {
    fontSize: 21,
    fontWeight: "900",
    color: "#29264E",
  },
  previousDayText: {
    fontSize: 14,
    color: "#666580",
    marginTop: 6,
    textAlign: "center",
  },
  boldText: {
    fontWeight: "900",
    color: "#29264E",
  },
  previousDayLocked: {
    fontSize: 12,
    color: "#88879D",
    marginTop: 7,
    fontWeight: "700",
  },
  speedWarning: {
    position: "absolute",
    left: 24,
    right: 24,
    bottom: 105,
    minHeight: 82,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.88)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    zIndex: 70,
    elevation: 15,
  },
  warningIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(101,117,241,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  warningContent: {
    flex: 1,
    marginLeft: 11,
  },
  warningTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: "#29264E",
  },
  warningText: {
    fontSize: 12,
    lineHeight: 17,
    color: "#696781",
    fontWeight: "600",
    marginTop: 2,
  },
  trendsHeader: {
    paddingHorizontal: 28,
    paddingTop: 25,
  },
  trendsTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#29264E",
  },
  trendsSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: "#77768B",
    marginTop: 5,
  },
  emptyFriends: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
    paddingBottom: 50,
  },
  friendsIcon: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    elevation: 5,
  },
  emptyFriendsTitle: {
    fontSize: 23,
    fontWeight: "900",
    color: "#29264E",
  },
  emptyFriendsText: {
    fontSize: 15,
    lineHeight: 21,
    color: "#77768B",
    textAlign: "center",
    marginTop: 7,
    maxWidth: 300,
  },
  addFriendButton: {
    height: 54,
    paddingHorizontal: 22,
    borderRadius: 27,
    backgroundColor: "#6575F1",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 22,
    elevation: 5,
  },
  addFriendText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  friendList: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  friendCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: 22,
    padding: 15,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    elevation: 3,
  },
  friendAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#A8B4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  friendAvatarText: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  friendInfo: {
    flex: 1,
    marginLeft: 12,
  },
  friendName: {
    fontSize: 16,
    fontWeight: "900",
    color: "#29264E",
  },
  friendAmount: {
    fontSize: 12,
    color: "#77768B",
    marginTop: 2,
  },
  friendBar: {
    height: 7,
    borderRadius: 4,
    backgroundColor: "#E2E6F1",
    marginTop: 7,
    overflow: "hidden",
  },
  friendProgress: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: "#6878EF",
  },
  friendPercent: {
    fontSize: 15,
    fontWeight: "900",
    color: "#6575F1",
    marginLeft: 8,
  },
});